// Package generator renders an example YAML manifest from a CRD's OpenAPIv3
// schema. The output is a yaml.Node tree carrying head-comments so each
// generated field is annotated with its description, required/optional status
// and any enum values.
package generator

import (
	"bytes"
	"encoding/json"
	"fmt"
	"math"
	"sort"
	"strconv"
	"strings"

	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"gopkg.in/yaml.v3"
)

// maxDepth guards against pathological schemas. Real-world CRDs are not
// recursive (CRD v1 forbids $ref), but a defensive cap costs us nothing.
const maxDepth = 64

// Generate builds a commented YAML manifest from the storage version of the
// supplied CustomResourceDefinition.
func Generate(crd *apiextensionsv1.CustomResourceDefinition) ([]byte, error) {
	ver, err := storageVersion(crd)
	if err != nil {
		return nil, err
	}
	if ver.Schema == nil || ver.Schema.OpenAPIV3Schema == nil {
		return nil, fmt.Errorf("CRD %s version %s has no openAPIV3Schema", crd.Name, ver.Name)
	}
	schema := ver.Schema.OpenAPIV3Schema

	apiVersion := ver.Name
	if crd.Spec.Group != "" {
		apiVersion = crd.Spec.Group + "/" + ver.Name
	}
	kind := crd.Spec.Names.Kind
	namespaced := crd.Spec.Scope == apiextensionsv1.NamespaceScoped

	root := &yaml.Node{Kind: yaml.MappingNode}

	banner := fmt.Sprintf("Generated by kubectl-crd-sample\nCRD:   %s\nKind:  %s\nScope: %s", crd.Name, kind, crd.Spec.Scope)
	addPair(root, key("apiVersion", banner), scalarStr(apiVersion))
	addPair(root, key("kind", ""), scalarStr(kind))

	meta := &yaml.Node{Kind: yaml.MappingNode}
	addPair(meta, key("name", ""), scalarStr("example"))
	if namespaced {
		addPair(meta, key("namespace", ""), scalarStr("default"))
	}
	addPair(root, key("metadata", ""), meta)

	// Emit user-defined top-level fields from the schema. `spec` first, then
	// any other custom fields alphabetically. apiVersion/kind/metadata/status
	// are intentionally skipped: the first three we render with concrete
	// values above, and `status` is a server-managed subresource that should
	// never appear in an applied manifest.
	skip := map[string]bool{"apiVersion": true, "kind": true, "metadata": true, "status": true}
	requiredSet := stringSet(schema.Required)

	var order []string
	if _, ok := schema.Properties["spec"]; ok {
		order = append(order, "spec")
	}
	for _, k := range sortedKeys(schema.Properties) {
		if skip[k] || k == "spec" {
			continue
		}
		order = append(order, k)
	}

	for _, name := range order {
		prop := schema.Properties[name]
		v, err := nodeFor(&prop, 0)
		if err != nil {
			return nil, fmt.Errorf("property %s: %w", name, err)
		}
		addPair(root, key(name, buildComment(&prop, requiredSet[name])), v)
	}

	doc := &yaml.Node{Kind: yaml.DocumentNode, Content: []*yaml.Node{root}}
	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(doc); err != nil {
		return nil, fmt.Errorf("encoding YAML: %w", err)
	}
	if err := enc.Close(); err != nil {
		return nil, fmt.Errorf("closing YAML encoder: %w", err)
	}
	return buf.Bytes(), nil
}

// storageVersion returns the CRD version marked storage=true.
func storageVersion(crd *apiextensionsv1.CustomResourceDefinition) (*apiextensionsv1.CustomResourceDefinitionVersion, error) {
	for i := range crd.Spec.Versions {
		v := &crd.Spec.Versions[i]
		if v.Storage {
			return v, nil
		}
	}
	return nil, fmt.Errorf("no storage version found for CRD %s", crd.Name)
}

// nodeFor renders an example value for a single schema node.
func nodeFor(s *apiextensionsv1.JSONSchemaProps, depth int) (*yaml.Node, error) {
	if s == nil {
		return scalarNull(), nil
	}
	if depth > maxDepth {
		n := scalarStr("...")
		n.LineComment = "max depth exceeded"
		return n, nil
	}

	// Honour explicit example/default first — they are authoritative.
	if v, ok := decodeJSON(s.Example); ok {
		return fromGoValue(v), nil
	}
	if v, ok := decodeJSON(s.Default); ok {
		return fromGoValue(v), nil
	}

	// Enums: emit the first allowed value. The full enum list is still
	// surfaced via the head-comment.
	if len(s.Enum) > 0 {
		if v, ok := decodeJSON(&s.Enum[0]); ok {
			return fromGoValue(v), nil
		}
	}

	switch s.Type {
	case "object":
		return objectNode(s, depth)
	case "array":
		return arrayNode(s, depth)
	case "string":
		return scalarStr(stringExample(s)), nil
	case "integer":
		return scalarTagged(integerExample(s), "!!int"), nil
	case "number":
		return scalarTagged(numberExample(s), "!!float"), nil
	case "boolean":
		return scalarTagged("false", "!!bool"), nil
	case "":
		// Untyped node — most commonly used with vendor extensions.
		if boolDeref(s.XPreserveUnknownFields) {
			n := &yaml.Node{Kind: yaml.MappingNode}
			return n, nil
		}
		if s.XIntOrString {
			return scalarTagged(integerExample(s), "!!int"), nil
		}
		return scalarNull(), nil
	default:
		return scalarStr("example"), nil
	}
}

func objectNode(s *apiextensionsv1.JSONSchemaProps, depth int) (*yaml.Node, error) {
	m := &yaml.Node{Kind: yaml.MappingNode}

	if len(s.Properties) > 0 {
		req := stringSet(s.Required)
		for _, name := range sortedKeys(s.Properties) {
			sub := s.Properties[name]
			v, err := nodeFor(&sub, depth+1)
			if err != nil {
				return nil, fmt.Errorf("%s: %w", name, err)
			}
			addPair(m, key(name, buildComment(&sub, req[name])), v)
		}
		return m, nil
	}

	// Free-form maps: synthesize a placeholder key.
	if s.AdditionalProperties != nil && s.AdditionalProperties.Schema != nil {
		v, err := nodeFor(s.AdditionalProperties.Schema, depth+1)
		if err != nil {
			return nil, err
		}
		addPair(m, key("key", "free-form key (additionalProperties)"), v)
		return m, nil
	}

	if boolDeref(s.XPreserveUnknownFields) {
		return m, nil
	}
	return m, nil
}

func arrayNode(s *apiextensionsv1.JSONSchemaProps, depth int) (*yaml.Node, error) {
	arr := &yaml.Node{Kind: yaml.SequenceNode}
	if s.Items != nil && s.Items.Schema != nil {
		// Emit at least one sample item, more if minItems demands it.
		n := 1
		if s.MinItems != nil && int(*s.MinItems) > n {
			n = int(*s.MinItems)
		}
		if s.MaxItems != nil && int(*s.MaxItems) < n {
			n = int(*s.MaxItems)
		}
		for i := 0; i < n; i++ {
			item, err := nodeFor(s.Items.Schema, depth+1)
			if err != nil {
				return nil, err
			}
			arr.Content = append(arr.Content, item)
		}
	}
	return arr, nil
}

// buildComment assembles the multi-line head comment for a single field.
// yaml.v3 prepends "# " to each newline-delimited line during encoding, so
// callers must not include the comment marker themselves.
func buildComment(s *apiextensionsv1.JSONSchemaProps, required bool) string {
	if s == nil {
		return ""
	}
	var lines []string

	if desc := strings.TrimSpace(s.Description); desc != "" {
		for _, ln := range strings.Split(desc, "\n") {
			lines = append(lines, strings.TrimRight(ln, " \t"))
		}
	}

	if required {
		lines = append(lines, "required")
	} else {
		lines = append(lines, "optional")
	}

	if len(s.Enum) > 0 {
		vals := make([]string, 0, len(s.Enum))
		for _, e := range s.Enum {
			vals = append(vals, strings.TrimSpace(string(e.Raw)))
		}
		lines = append(lines, "enum: ["+strings.Join(vals, ", ")+"]")
	}

	return strings.Join(lines, "\n")
}

// --- yaml.Node helpers ---------------------------------------------------

func key(name, headComment string) *yaml.Node {
	return &yaml.Node{
		Kind:        yaml.ScalarNode,
		Tag:         "!!str",
		Value:       name,
		HeadComment: headComment,
	}
}

func addPair(parent, k, v *yaml.Node) {
	parent.Content = append(parent.Content, k, v)
}

func scalarStr(s string) *yaml.Node {
	n := &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: s}
	if s == "" {
		// An unquoted empty scalar would emit as `null`; force quotes so the
		// generated manifest stays YAML-valid as a string field.
		n.Style = yaml.DoubleQuotedStyle
	}
	return n
}

func scalarTagged(value, tag string) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: tag, Value: value}
}

func scalarNull() *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!null", Value: "null"}
}

// fromGoValue marshals an arbitrary Go value (decoded from JSON) into a YAML
// node. Used for examples, defaults, and enum picks.
func fromGoValue(v any) *yaml.Node {
	n := &yaml.Node{}
	if err := n.Encode(v); err != nil {
		return scalarStr(fmt.Sprintf("%v", v))
	}
	return n
}

// decodeJSON unmarshals a *apiextensionsv1.JSON into a generic Go value.
// The boolean indicates whether a value was actually present.
func decodeJSON(j *apiextensionsv1.JSON) (any, bool) {
	if j == nil || len(j.Raw) == 0 {
		return nil, false
	}
	var v any
	if err := json.Unmarshal(j.Raw, &v); err != nil {
		return nil, false
	}
	return v, true
}

// stringExample returns a placeholder for a typed string field that satisfies
// the schema's minLength / maxLength constraints. Pattern is not evaluated; if
// the schema specifies a pattern, the caller may need to tweak the value.
func stringExample(s *apiextensionsv1.JSONSchemaProps) string {
	var val string
	switch s.Format {
	case "date-time":
		val = "1970-01-01T00:00:00Z"
	case "date":
		val = "1970-01-01"
	case "time":
		val = "00:00:00Z"
	case "byte":
		val = "ZXhhbXBsZQ==" // base64("example")
	case "duration":
		val = "1h"
	case "email":
		val = "user@example.com"
	case "hostname":
		val = "example.com"
	case "ipv4":
		val = "127.0.0.1"
	case "ipv6":
		val = "::1"
	case "uri", "url":
		val = "https://example.com"
	case "uuid":
		val = "00000000-0000-0000-0000-000000000000"
	default:
		val = "example"
	}

	if s.MinLength != nil {
		for int64(len(val)) < *s.MinLength {
			val += "x"
		}
	}
	if s.MaxLength != nil && int64(len(val)) > *s.MaxLength {
		val = val[:*s.MaxLength]
	}
	return val
}

// integerExample returns a placeholder integer that lies inside the schema's
// [minimum, maximum] window (honouring the exclusive flags) and is a multiple
// of multipleOf when specified.
func integerExample(s *apiextensionsv1.JSONSchemaProps) string {
	val := int64(0)
	if s.Minimum != nil {
		val = int64(math.Ceil(*s.Minimum))
		if s.ExclusiveMinimum && float64(val) == *s.Minimum {
			val++
		}
	}
	if s.MultipleOf != nil && *s.MultipleOf > 0 {
		step := int64(*s.MultipleOf)
		if step > 0 && val%step != 0 {
			val += step - (val % step)
		}
	}
	if s.Maximum != nil {
		max := int64(math.Floor(*s.Maximum))
		if s.ExclusiveMaximum && float64(max) == *s.Maximum {
			max--
		}
		if val > max {
			val = max
		}
	}
	return strconv.FormatInt(val, 10)
}

// numberExample returns a placeholder floating-point value that satisfies the
// schema's minimum / maximum constraints.
func numberExample(s *apiextensionsv1.JSONSchemaProps) string {
	val := 0.0
	if s.Minimum != nil {
		val = *s.Minimum
		if s.ExclusiveMinimum {
			val = math.Nextafter(val, math.Inf(1))
		}
	}
	if s.Maximum != nil {
		max := *s.Maximum
		if s.ExclusiveMaximum {
			max = math.Nextafter(max, math.Inf(-1))
		}
		if val > max {
			val = max
		}
	}
	return strconv.FormatFloat(val, 'f', -1, 64)
}

func sortedKeys(m map[string]apiextensionsv1.JSONSchemaProps) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func stringSet(ss []string) map[string]bool {
	m := make(map[string]bool, len(ss))
	for _, s := range ss {
		m[s] = true
	}
	return m
}

func boolDeref(b *bool) bool {
	return b != nil && *b
}
