name: Release with GoReleaser

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write
  attestations: write
  security-events: write

jobs:
  Release:
    name: Run GoReleaser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v4
        continue-on-error: true
        with:
          subject-path: |
            dist/kubectl-crd-sample_darwin_amd64_v1/*
            dist/kubectl-crd-sample_darwin_arm64_v8.0/*
            dist/kubectl-crd-sample_linux_amd64_v1/*
            dist/kubectl-crd-sample_linux_arm64_v8.0/*
            dist/kubectl-crd-sample_windows_amd64_v1/*
            dist/kubectl-crd-sample_windows_arm64_v8.0/*

      # - name: Update new version in krew-index
      #   uses: rajatjindal/krew-release-bot@v0.0.51
